package com.crowdshelf.app.io;

/**
 * Created by Torstein on 21.09.2015.
 */
public enum DBEventType {
    USER_CHANGED,
    BOOK_CHANGED,
    BOOKINFO_CHANGED,
    CROWD_CHANGED,
    USER_BOOKS_CHANGED,
    CROWD_BOOKS_CHANGED,

    USER_CREATED,
    BOOK_CREATED,
    CROWD_CREATED,

    CREATE_BOOK_AFTER_ADD,
    ADD_BOOK_USERSHELF,
    SCAN_COMPLETE_GET_BOOKINFO,
    BOOK_INFO_RECEIVED_ADD_TO_USERSHELF, BOOK_REMOVED, GET_BOOK_AFTER_ADD, LOGIN
}
